import os
import sys
import streamlit as st
from dotenv import load_dotenv

load_dotenv()

current_dir = os.path.dirname(os.path.abspath(__file__))
project_root = os.path.abspath(os.path.join(current_dir, "../../../.."))
if project_root not in sys.path:
    sys.path.insert(0, project_root)

from src.agents.ifc.rag_agents import QueryExpansionAgent
# Import your newly written batch LLM Reranker
from src.agents.helpers.rerank import LLMMaterialReranker
from src.utils.load_conf import load_config, build_cfg

CONFIG_PATH = os.environ.get("CONFIG_PATH", None)
config = build_cfg(CONFIG_PATH)


def render_material_space(query: str, cfg: dict, mat_search_service: any, edges_db: list, reranker_model: str, top_k: int):
    """
    Executes an optimized vector retrieval pipeline followed by a global
    generative batch LLM Reranker matrix over unique metadata and variation arrays.
    """
    # Fix: Safely clear out the asymmetric routing prefix if passed down natively
    cleaned_query = query.lower()
    for word in ["find ", "search for ", "look up ", "get ", "query: "]:
        cleaned_query = cleaned_query.replace(word, "")
    cleaned_query = cleaned_query.strip()

    # Early exit if the text field is empty
    if not cleaned_query:
        return

    # Step 1: Agentic Translation Expansion
    with st.spinner("Executing Agentic Pre-RAG Expansion..."):
        expansion_agent = QueryExpansionAgent(config=cfg)
        expanded_payload = expansion_agent.expand(cleaned_query, domain="IFC Materials")

        raw_synonyms = expanded_payload.get("synonyms", [cleaned_query])
        search_string = expanded_payload.get("expanded_query", cleaned_query)
        
        if cleaned_query not in raw_synonyms:
            raw_synonyms.append(cleaned_query)

        # FIX: Filter out empty strings or whitespaces generated by the LLM Translation parser loop
        synonyms_list = [str(s).strip() for s in raw_synonyms if s and str(s).strip()]

        st.caption(f"🔮 **Agent Search Vector:** `{search_string}`")
        st.caption(f"🌍 **Targeted Translations:** `{synonyms_list}`")

    # Step 2: Query the Vector Store with clean Multi-Language targets
    with st.spinner("Gathering multi-language candidate nodes..."):
        # We use a dictionary to group the flattened variant vector hits by their true base material root
        aggregated_candidates = {}
        
        for term in synonyms_list:
            # Skip empty terms defensively
            if not term.strip():
                continue
                
            term_hits = mat_search_service.search(query=term, limit=top_k)
            if term_hits:
                for hit in term_hits:
                    # Parse out ID and Metadata values safely
                    if isinstance(hit, dict):
                        hit_id = hit.get("id") or hit.get("material_id")
                        metadata = hit.get("metadata") or hit.get("payload") or {}
                    else:
                        hit_id = getattr(hit, "id", None) or getattr(hit, "material_id", None) or str(hit)
                        metadata = getattr(hit, "metadata", {}) or getattr(hit, "payload", {})

                    if hit_id:
                        # Normalize string (e.g., "B064_01_Formigó Estructural##var_6" -> "B064_01_Formigó Estructural")
                        base_material_id = hit_id.split("##var_")[0]
                        variant_term = metadata.get("variant_term") or base_material_id.split("_")[-1]

                        # If this base material hasn't been added yet, initialize its structural payload
                        if base_material_id not in aggregated_candidates:
                            aggregated_candidates[base_material_id] = {
                                "id": hit_id, # Keeps the highest matching raw ID entry point
                                "metadata": {
                                    "clean_name": metadata.get("clean_name", base_material_id),
                                    "variations": [] # We will dynamically fill this array!
                                }
                            }
                        
                        # Append the variant term to the consolidated array if it isn't already noted
                        if variant_term not in aggregated_candidates[base_material_id]["metadata"]["variations"]:
                            aggregated_candidates[base_material_id]["metadata"]["variations"].append(variant_term)

        # Convert the aggregated dictionary maps back into a clean flat list for the Reranker agent
        raw_hits = list(aggregated_candidates.values())

    # Step 3: Handle Fallbacks or Execute Agentic Reranking
    if not raw_hits:
        st.warning("⚠️ Vector space returned 0 hits. Falling back to string match...")
        fallback_matches = set()
        for edge in edges_db:
            mat_id = edge.get("material_id", "")
            if any(s.lower() in mat_id.lower() for s in synonyms_list):
                fallback_matches.add(mat_id)
        
        if fallback_matches:
            st.success(f"🔍 Direct string scan recovered **{len(fallback_matches)}** records:")
            for mat_id in sorted(list(fallback_matches))[:top_k]:
                with st.expander(f"🧪 Material (Relational Match): **{mat_id}**", expanded=True):
                    render_linked_typologies(mat_id, edges_db)
    else:
        # ── LLM BATCH RERANKER INTERACTION GATE ────────────────────────────
        with st.spinner("Invoking LLM to execute global comparative sorting matrix..."):
            llm_reranker = LLMMaterialReranker(config=cfg)
            
            # Now contains only 1 cleanly populated representative item per physical material document
            ranked_results = llm_reranker.rerank(user_query=cleaned_query, candidates=raw_hits)
            
        st.success(f"🎯 Discovered and Globally Ordered **{len(ranked_results)}** Distinct Material Configurations:")
        st.divider()

        # Render out the results returned by your LLM structured schema
        for item in ranked_results[:top_k]:
            mat_id = item.get("raw_id")
            display_name = item.get("display_name")
            relevance_score = item.get("relevance_score")
            justification = item.get("justification")

            header_title = f"🧪 {display_name} [Raw ID: {mat_id}] (LLM Score: {relevance_score:.4f})"
            
            with st.expander(header_title, expanded=True):
                if justification:
                    st.markdown(f"**🤖 Rerank Justification:** *{justification}*")
                
                # Split tracking labels back out to search the relational graph mappings safely
                base_graph_id = mat_id.split("##var_")[0]
                render_linked_typologies(base_graph_id, edges_db)


def render_linked_typologies(mat_id: str, edges_db: list):
    """Helper to render graph linkages."""
    linked_typos = sorted(list({e["mapped_typology_id"] for e in edges_db if e.get("material_id") == mat_id}))
    if linked_typos:
        st.markdown(f"**Utilized across the following structural typologies ({len(linked_typos)}):**")
        for typo in linked_typos:
            st.markdown(f"* 🏗️ `{typo}`")
    else:
        st.caption("No typology linkages registered for this material in the structural graph map.")